<h3 class="devsite-page-title"><span style="color: #ffff99;">tf.keras.datasets.imdb.load_data:</span></h3>
<ul>
<li><span style="color: #ffff99;"><strong><code>path</code></strong>: where to cache the data (relative to&nbsp;<code>~/.keras/dataset</code>).</span></li>
<li><span style="color: #ffff99;"><strong><code>num_words</code></strong>: max number of words to include. Words are ranked by how often they occur (in the training set) and only the most frequent words are kept</span></li>
<li><span style="color: #ffff99;"><strong><code>maxlen</code></strong>: sequences longer than this will be filtered out.</span></li>
<li><span style="color: #ffff99;"><strong><code>seed</code></strong>: random seed for sample shuffling</span></li>
<li>
<p><span style="color: #ffff99;"><strong>returnes</strong>:Tuple of Numpy arrays:&nbsp;<code>(x_train, y_train), (x_test, y_test)</code>.</span></p>
</li>
</ul>

In [15]:
from tensorflow import keras
from keras.datasets import imdb
from keras import preprocessing

# Number of words to consider as features
max_features = 5000
# Cuts off the text after this number of words (among the max_features most common words)
max_len = 50
imdb_path='D:\CSV original\imdb.npz'
# Loads the data as lists of integers
(x_train, y_train), (x_test, y_test) = imdb.load_data(path=imdb_path,num_words=max_features)
print(x_train.shape)
print(x_train[0])
x_train


(25000,)
[1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 2, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 2, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 2, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 2, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 2, 19, 178, 32]


array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 2, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 2, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 2, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 2, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 2, 19, 178, 32]),
       list([1, 194, 1153, 194, 2, 78, 228, 5, 6, 1463, 4369,

In [17]:
# preprocessing.sequence.pad_sequences:
# Turns the lists of integers into a 2D integer tensor of shape (samples, max_len)
#   This function transforms a list of num_samples sequences (lists of integers) into a 2D Numpy array of shape (num_samples, num_timesteps). 
# num_timesteps is either the maxlen argument if provided, or the length of the longest sequence otherwise
# x_train = preprocessing.sequence.pad_sequences(x_train, maxlen=max_len)
x_train = keras.utils.pad_sequences(x_train, maxlen=max_len)
x_test =keras.utils.pad_sequences(x_test, maxlen=max_len)

#
print(x_train.shape)
print(x_test.shape)
print(x_train)
print(x_train[0])
x_train[0]

(25000, 50)
(25000, 50)
[[2071   56   26 ...   19  178   32]
 [   2    5    2 ...   16  145   95]
 [ 215   28  610 ...    7  129  113]
 ...
 [   4   65  496 ...    4 3586    2]
 [  13   18   31 ...   12    9   23]
 [   2    8 2197 ...  204  131    9]]
[2071   56   26  141    6  194    2   18    4  226   22   21  134  476
   26  480    5  144   30    2   18   51   36   28  224   92   25  104
    4  226   65   16   38 1334   88   12   16  283    5   16 4472  113
  103   32   15   16    2   19  178   32]


array([2071,   56,   26,  141,    6,  194,    2,   18,    4,  226,   22,
         21,  134,  476,   26,  480,    5,  144,   30,    2,   18,   51,
         36,   28,  224,   92,   25,  104,    4,  226,   65,   16,   38,
       1334,   88,   12,   16,  283,    5,   16, 4472,  113,  103,   32,
         15,   16,    2,   19,  178,   32])

In [14]:
print(x_train[0])


[2071   56   26  141    6  194    2   18    4  226   22   21  134  476
   26  480    5  144   30    2   18   51   36   28  224   92   25  104
    4  226   65   16   38 1334   88   12   16  283    5   16 4472  113
  103   32   15   16    2   19  178   32]


<ul>
<li>
<p><span style="color: #ffff99;">The network will learn 8-dimensional embeddings for each of the 10,000 words(5000 words I think), turn the input integer sequences (2D integer tensor) into embedded sequences (3D float tensor), flatten the tensor to 2D, and train a single Dense layer on top for classificationNumpy arrays:&nbsp;<code>(x_train, y_train), (x_test, y_test)</code>.</span></p>
</li>
</ul>

<ul>
<li><span style="color: #99ccff;"><code>kernel_regularizer</code>: Regularizer to apply a penalty on the layer's kernel</span></li>
<li style="list-style-type: none;"></li>
<li><span style="color: #99ccff;"><code>bias_regularizer</code>: Regularizer to apply a penalty on the layer's bias</span></li>
<li style="list-style-type: none;"></li>
<li><span style="color: #99ccff;"><code>activity_regularizer</code>: Regularizer to apply a penalty on the layer's output</span></li>
</ul>

In [18]:
from keras.models import Sequential
from keras.layers import Embedding, Flatten, Dropout, Dense
from keras import regularizers

regularizer = regularizers.l2(l2=1e-5)  #A regularizer that applies a L2 regularization penalty 
                                        #l2: Float; L2 regularization factor which is multiplied by sum squared of weights

model = Sequential()

# Specifies the maximum input length to the Embedding layer so you can later
# flatten the embedded inputs. After the Embedding layer, the activations
# have shape (samples, max_len, 8).     #samples may be the batches
model.add(Embedding(max_features, 8, input_length=max_len))

# Flattens the 3D tensor of embeddings into a 2D tensor of shape (samples, max_len * 8)
model.add(Flatten())

# 
model.add(Dropout(0.5))

# Adds the classifier on top
model.add(Dense(1, activation='sigmoid', kernel_regularizer=regularizer))

# compile model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])

model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 50, 8)             40000     
                                                                 
 flatten (Flatten)           (None, 400)               0         
                                                                 
 dropout (Dropout)           (None, 400)               0         
                                                                 
 dense (Dense)               (None, 1)                 401       
                                                                 
Total params: 40,401
Trainable params: 40,401
Non-trainable params: 0
_________________________________________________________________


<p><span style="color: #00ccff;">40000=5000(num of all frequently occured words)*8</span></p>

In [19]:

# fit model
history = model.fit(x_train, y_train,
                    epochs=50,
                    batch_size=32,
                    validation_data=(x_test, y_test))

Epoch 1/50
782/782 [==============================] - 5s 4ms/step - loss: 0.6436 - acc: 0.6388 - val_loss: 0.5213 - val_acc: 0.7820
Epoch 2/50
782/782 [==============================] - 3s 4ms/step - loss: 0.4544 - acc: 0.7972 - val_loss: 0.4174 - val_acc: 0.8129
Epoch 3/50
782/782 [==============================] - 3s 4ms/step - loss: 0.3856 - acc: 0.8300 - val_loss: 0.3953 - val_acc: 0.8222
Epoch 4/50
782/782 [==============================] - 3s 4ms/step - loss: 0.3522 - acc: 0.8450 - val_loss: 0.3929 - val_acc: 0.8218
Epoch 5/50
782/782 [==============================] - 3s 3ms/step - loss: 0.3318 - acc: 0.8571 - val_loss: 0.3943 - val_acc: 0.8202
Epoch 6/50
782/782 [==============================] - 3s 3ms/step - loss: 0.3150 - acc: 0.8650 - val_loss: 0.4004 - val_acc: 0.8186
Epoch 7/50
782/782 [==============================] - 3s 3ms/step - loss: 0.2992 - acc: 0.8726 - val_loss: 0.4038 - val_acc: 0.8180
Epoch 8/50
782/782 [==============================] - 3s 4ms/step - loss: 0.

<p><span style="color: #ffcc99;">You get to a validation accuracy of ~80%, which is pretty good considering that you&rsquo;re only looking at the first 40 words in every review. But note that merely flattening the embedded sequences and training a single Dense layer on top leads to a model that treats each word in the input sequence separately, without considering inter-word relationships and sentence structure (for example, this model would likely treat both &ldquo;this movie is a bomb&rdquo; and &ldquo;this movie is the bomb&rdquo; as being negative reviews). It&rsquo;s much better to add recurrent layers or 1D convolutional layers on top of the embedded sequences to learn features that take into account each sequence as a whole</span></p>

In [21]:
len(model.layers)


4

In [23]:

model.layers[0]

In [27]:
model.layers[0].get_weights()[0]

array([[-0.01292851, -0.02741463,  0.01828118, ..., -0.02984082,
        -0.01374053,  0.03701801],
       [-0.03744171,  0.20749305,  0.0353387 , ..., -0.02239804,
        -0.27819154, -0.2838543 ],
       [ 0.01137996, -0.01576446, -0.00433339, ..., -0.01342939,
         0.00468019, -0.00202242],
       ...,
       [-0.13871156, -0.20225592,  0.43030393, ...,  0.39271358,
        -0.13846624, -0.4254482 ],
       [ 0.13126855,  0.400036  , -0.4124019 , ..., -0.51967186,
         0.00446057,  0.09763086],
       [ 0.6401965 , -0.588739  , -0.5614418 , ...,  0.19014515,
         0.58151495,  0.3470655 ]], dtype=float32)

In [28]:

weights = model.layers[0].get_weights()[0]
print(weights.shape)

(5000, 8)
